/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  /home/nicrizzo/gengetopt-2.23/src/gengetopt --input=./command-line-parsing/config.ggo --output-dir=./command-line-parsing/ --unnamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Program to perform colinear chaining on Elastic Founder Graphs";

const char *gengetopt_args_info_usage = "Usage: chainx-block-graph (--global|--semi-global) graph.gfa anchors.gaf output.gaf";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "The program takes in input an Elastic Founder Graph (xGFA) and exact matches\nbetween text queries and the graph (GAF), it computes the anchor-restricted\nedit distance between the queries and the (relaxation of the) graph, and\noutputs the corresponding chain in GAF format.";

const char *gengetopt_args_info_full_help[] = {
  "  -h, --help                    Print help and exit",
  "      --full-help               Print help, including hidden options, and exit",
  "  -V, --version                 Print version and exit",
  "      --chain-to-eds            Perform chaining on the Elastic Degenerate\n                                  String relaxation of the graph (currently the\n                                  only implemented chaining solution)\n                                  (default=on)",
  "  -g, --global                  Chain between the whole query and any maximal\n                                  graph path  (default=off)",
  "  -s, --semi-global             Chain between the whole query and any graph\n                                  subpath  (default=off)",
  "      --unsorted-input          Do not assume the input GAF anchors to be\n                                  sorted (at the cost of loading all anchors)\n                                  (default=off)",
  "      --no-split-output-matches Do not split edge matches into node matches in\n                                  the output chains  (default=off)",
  "      --initial-guess=GUESS     Fix a constant starting guess for the cost of\n                                  the optimal chain  (default=`100')",
  "      --initial-guess-coverage=GUESS\n                                Have the starting guess for the optimal cost be\n                                  a fraction of the inverse coverage of the\n                                  read (GUESS * (read length - read coverage))\n                                  instead of a constant (by default this is\n                                  disabled)  (default=`0')",
  "      --ramp-up-factor=RAMPUP   At each chaining iteration, multiply by RAMPUP\n                                  the guess for the cost of the optimal chain\n                                  (default=`4.0')",
  "  -a, --alternative-chains=N    Chain N+1 times, removing the used anchors\n                                  after each execution, and output all chains\n                                  (default=`0')",
  "  -t, --threads=THREADNUM       Max # threads  (default=`-1')",
  "      --overwrite               Overwrite the output file, if it exists\n                                  (default=off)",
  "      --split-output-matches-graphaligner\n                                Filter out node matches of length 1 for use in\n                                  GraphAligner  (default=off)",
    0
};

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_full_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_full_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_full_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_full_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_full_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_full_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_full_help[6];
  gengetopt_args_info_help[7] = gengetopt_args_info_full_help[7];
  gengetopt_args_info_help[8] = gengetopt_args_info_full_help[8];
  gengetopt_args_info_help[9] = gengetopt_args_info_full_help[9];
  gengetopt_args_info_help[10] = gengetopt_args_info_full_help[10];
  gengetopt_args_info_help[11] = gengetopt_args_info_full_help[11];
  gengetopt_args_info_help[12] = gengetopt_args_info_full_help[12];
  gengetopt_args_info_help[13] = gengetopt_args_info_full_help[13];
  gengetopt_args_info_help[14] = 0; 
  
}

const char *gengetopt_args_info_help[15];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_LONG
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->chain_to_eds_given = 0 ;
  args_info->global_given = 0 ;
  args_info->semi_global_given = 0 ;
  args_info->unsorted_input_given = 0 ;
  args_info->no_split_output_matches_given = 0 ;
  args_info->initial_guess_given = 0 ;
  args_info->initial_guess_coverage_given = 0 ;
  args_info->ramp_up_factor_given = 0 ;
  args_info->alternative_chains_given = 0 ;
  args_info->threads_given = 0 ;
  args_info->overwrite_given = 0 ;
  args_info->split_output_matches_graphaligner_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->chain_to_eds_flag = 1;
  args_info->global_flag = 0;
  args_info->semi_global_flag = 0;
  args_info->unsorted_input_flag = 0;
  args_info->no_split_output_matches_flag = 0;
  args_info->initial_guess_arg = 100;
  args_info->initial_guess_orig = NULL;
  args_info->initial_guess_coverage_arg = 0;
  args_info->initial_guess_coverage_orig = NULL;
  args_info->ramp_up_factor_arg = 4.0;
  args_info->ramp_up_factor_orig = NULL;
  args_info->alternative_chains_arg = 0;
  args_info->alternative_chains_orig = NULL;
  args_info->threads_arg = -1;
  args_info->threads_orig = NULL;
  args_info->overwrite_flag = 0;
  args_info->split_output_matches_graphaligner_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{

  init_help_array(); 
  args_info->help_help = gengetopt_args_info_full_help[0] ;
  args_info->full_help_help = gengetopt_args_info_full_help[1] ;
  args_info->version_help = gengetopt_args_info_full_help[2] ;
  args_info->chain_to_eds_help = gengetopt_args_info_full_help[3] ;
  args_info->global_help = gengetopt_args_info_full_help[4] ;
  args_info->semi_global_help = gengetopt_args_info_full_help[5] ;
  args_info->unsorted_input_help = gengetopt_args_info_full_help[6] ;
  args_info->no_split_output_matches_help = gengetopt_args_info_full_help[7] ;
  args_info->initial_guess_help = gengetopt_args_info_full_help[8] ;
  args_info->initial_guess_coverage_help = gengetopt_args_info_full_help[9] ;
  args_info->ramp_up_factor_help = gengetopt_args_info_full_help[10] ;
  args_info->alternative_chains_help = gengetopt_args_info_full_help[11] ;
  args_info->threads_help = gengetopt_args_info_full_help[12] ;
  args_info->overwrite_help = gengetopt_args_info_full_help[13] ;
  args_info->split_output_matches_graphaligner_help = gengetopt_args_info_full_help[14] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->initial_guess_orig));
  free_string_field (&(args_info->initial_guess_coverage_orig));
  free_string_field (&(args_info->ramp_up_factor_orig));
  free_string_field (&(args_info->alternative_chains_orig));
  free_string_field (&(args_info->threads_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->chain_to_eds_given)
    write_into_file(outfile, "chain-to-eds", 0, 0 );
  if (args_info->global_given)
    write_into_file(outfile, "global", 0, 0 );
  if (args_info->semi_global_given)
    write_into_file(outfile, "semi-global", 0, 0 );
  if (args_info->unsorted_input_given)
    write_into_file(outfile, "unsorted-input", 0, 0 );
  if (args_info->no_split_output_matches_given)
    write_into_file(outfile, "no-split-output-matches", 0, 0 );
  if (args_info->initial_guess_given)
    write_into_file(outfile, "initial-guess", args_info->initial_guess_orig, 0);
  if (args_info->initial_guess_coverage_given)
    write_into_file(outfile, "initial-guess-coverage", args_info->initial_guess_coverage_orig, 0);
  if (args_info->ramp_up_factor_given)
    write_into_file(outfile, "ramp-up-factor", args_info->ramp_up_factor_orig, 0);
  if (args_info->alternative_chains_given)
    write_into_file(outfile, "alternative-chains", args_info->alternative_chains_orig, 0);
  if (args_info->threads_given)
    write_into_file(outfile, "threads", args_info->threads_orig, 0);
  if (args_info->overwrite_given)
    write_into_file(outfile, "overwrite", 0, 0 );
  if (args_info->split_output_matches_graphaligner_given)
    write_into_file(outfile, "split-output-matches-graphaligner", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_LONG:
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_LONG:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "chain-to-eds",	0, NULL, 0 },
        { "global",	0, NULL, 'g' },
        { "semi-global",	0, NULL, 's' },
        { "unsorted-input",	0, NULL, 0 },
        { "no-split-output-matches",	0, NULL, 0 },
        { "initial-guess",	1, NULL, 0 },
        { "initial-guess-coverage",	1, NULL, 0 },
        { "ramp-up-factor",	1, NULL, 0 },
        { "alternative-chains",	1, NULL, 'a' },
        { "threads",	1, NULL, 't' },
        { "overwrite",	0, NULL, 0 },
        { "split-output-matches-graphaligner",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVgsa:t:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'g':	/* Chain between the whole query and any maximal graph path.  */
        
        
          if (update_arg((void *)&(args_info->global_flag), 0, &(args_info->global_given),
              &(local_args_info.global_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "global", 'g',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Chain between the whole query and any graph subpath.  */
        
        
          if (update_arg((void *)&(args_info->semi_global_flag), 0, &(args_info->semi_global_given),
              &(local_args_info.semi_global_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "semi-global", 's',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Chain N+1 times, removing the used anchors after each execution, and output all chains.  */
        
        
          if (update_arg( (void *)&(args_info->alternative_chains_arg), 
               &(args_info->alternative_chains_orig), &(args_info->alternative_chains_given),
              &(local_args_info.alternative_chains_given), optarg, 0, "0", ARG_LONG,
              check_ambiguity, override, 0, 0,
              "alternative-chains", 'a',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Max # threads.  */
        
        
          if (update_arg( (void *)&(args_info->threads_arg), 
               &(args_info->threads_orig), &(args_info->threads_given),
              &(local_args_info.threads_given), optarg, 0, "-1", ARG_LONG,
              check_ambiguity, override, 0, 0,
              "threads", 't',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            cmdline_parser_print_full_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Perform chaining on the Elastic Degenerate String relaxation of the graph (currently the only implemented chaining solution).  */
          if (strcmp (long_options[option_index].name, "chain-to-eds") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->chain_to_eds_flag), 0, &(args_info->chain_to_eds_given),
                &(local_args_info.chain_to_eds_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "chain-to-eds", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not assume the input GAF anchors to be sorted (at the cost of loading all anchors).  */
          else if (strcmp (long_options[option_index].name, "unsorted-input") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->unsorted_input_flag), 0, &(args_info->unsorted_input_given),
                &(local_args_info.unsorted_input_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "unsorted-input", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not split edge matches into node matches in the output chains.  */
          else if (strcmp (long_options[option_index].name, "no-split-output-matches") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->no_split_output_matches_flag), 0, &(args_info->no_split_output_matches_given),
                &(local_args_info.no_split_output_matches_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "no-split-output-matches", '-',
                additional_error))
              goto failure;
          
          }
          /* Fix a constant starting guess for the cost of the optimal chain.  */
          else if (strcmp (long_options[option_index].name, "initial-guess") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->initial_guess_arg), 
                 &(args_info->initial_guess_orig), &(args_info->initial_guess_given),
                &(local_args_info.initial_guess_given), optarg, 0, "100", ARG_LONG,
                check_ambiguity, override, 0, 0,
                "initial-guess", '-',
                additional_error))
              goto failure;
          
          }
          /* Have the starting guess for the optimal cost be a fraction of the inverse coverage of the read (GUESS * (read length - read coverage)) instead of a constant (by default this is disabled).  */
          else if (strcmp (long_options[option_index].name, "initial-guess-coverage") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->initial_guess_coverage_arg), 
                 &(args_info->initial_guess_coverage_orig), &(args_info->initial_guess_coverage_given),
                &(local_args_info.initial_guess_coverage_given), optarg, 0, "0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "initial-guess-coverage", '-',
                additional_error))
              goto failure;
          
          }
          /* At each chaining iteration, multiply by RAMPUP the guess for the cost of the optimal chain.  */
          else if (strcmp (long_options[option_index].name, "ramp-up-factor") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->ramp_up_factor_arg), 
                 &(args_info->ramp_up_factor_orig), &(args_info->ramp_up_factor_given),
                &(local_args_info.ramp_up_factor_given), optarg, 0, "4.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "ramp-up-factor", '-',
                additional_error))
              goto failure;
          
          }
          /* Overwrite the output file, if it exists.  */
          else if (strcmp (long_options[option_index].name, "overwrite") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->overwrite_flag), 0, &(args_info->overwrite_given),
                &(local_args_info.overwrite_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "overwrite", '-',
                additional_error))
              goto failure;
          
          }
          /* Filter out node matches of length 1 for use in GraphAligner.  */
          else if (strcmp (long_options[option_index].name, "split-output-matches-graphaligner") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->split_output_matches_graphaligner_flag), 0, &(args_info->split_output_matches_graphaligner_given),
                &(local_args_info.split_output_matches_graphaligner_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "split-output-matches-graphaligner", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



	FIX_UNUSED(check_required);

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
