#!/bin/bash
set -e
set -o pipefail
thisfolder=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) # https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script

# executables' absolute paths/commands (make sure they work!)
graphaligner=$thisfolder/tools/GraphAligner/bin/GraphAligner
gcsa2locate=$thisfolder/tools/gcsa2-locate/gcsa2-locate

# default params
workingfolder="."
threads=8 # threads
edgelongestcount=0
extendoptions="--max-cluster-extend 5 -b 10" # GraphAligner default extend options
discardoption="(substr(\$16,6) > 0.90) && ((\$4-\$3)*100/\$2 >= 50)" # using -c option, discard alignments with identity <= 90% or read coverage < 50%

print_help()
{
   echo "Pipeline to align long reads to vg graphs/GCSA2 indexes based on semi-repeat-free seeds"
   echo "usage: SRFAligner -g graph.gfa -s index.gcsa -f reads.fastq -a alignments.gaf"
   echo "	-h --help:  show this screen"
   echo "	-g graph.gfa: vg graph in GFA format"
   echo "	-s index.gcsa: GCSA2 index of the graph"
   echo "	-f reads.fastq: reads in FASTQ format"
   echo "	-a alignmentsout.gaf: output alignments in GAF format"
   echo "	-t threads: # of threads"
   echo "	-i IGNORECHARS : ignore the following characters for indexability/seed finding"
   echo "	-c : call GraphAligner with more expensive extend options"
   echo "	-p : disable pipeline mode and save the seeds in working folder"
   echo "	-o edgelongestcount: heuristic parameter for seed computation (see gcsa2-locate)"
   echo "	-w path: working folder for output and temporary files"
}

# https://stackoverflow.com/questions/12022592/how-can-i-use-long-options-with-the-bash-getopts-builtin
for arg in "$@"; do
	shift
	case "$arg" in
		'--help')                set -- "$@" '-h'   ;;
		*)                       set -- "$@" "$arg" ;;
	esac
done

while getopts "hepcg:f:a:t:w:i:o:s:" option; do
	case $option in
		h) # display help
			print_help
			exit;;
		g) # graph
			argg=true
			graph="$OPTARG" ;;
		s) # index
			args=true
			index="$OPTARG" ;;
		f) # fastq reads
			argf=true
			reads="$OPTARG" ;;
		a) # output
			arga=true
			alignmentsout="$OPTARG" ;;
		t) # threads
			argt=true
			threads="$OPTARG" ;;
		i) # ignorechars
			argi=true
			ignorechars="$OPTARG" ;;
		w) # working folder
			argw=true
			workingfolder="$OPTARG" ;;
		c) # extendplus
			argc=true ;;
		p) # disable pipeline mode flag
			argp=true ;;
		e) # extend all clusters
			arge=true ;;
		o) # edgelongestcount parameter
			argo=true
			edgelongestcount="$OPTARG" ;;
		\?) # invalid option
			echo "Error: Invalid option"
			print_help
			exit;;
	esac
done
if [[ "$argg" != true ]] || [[ "$argf" != true ]] || [[ "$args" != true ]] ; then
	print_help
	exit
fi
if [[ "$argc" = true ]] && [[ "$arge" = true ]] ; then
	print_help
	exit
fi

ignorecharsarg=""
if [[ "$argi" = true ]] ; then
	ignorecharsarg="--ignore-chars=$ignorechars"
fi
if [[ "$argc" = true ]] ; then
	extendoptions="--max-cluster-extend 10 -b 50"
fi
if [[ "$arge" = true ]] ; then
	extendoptions="--max-cluster-extend -1 --multimap-score-fraction 0.00 -b 10"
fi

# move to working folder
if [[ "$argw" = true ]] ; then
	workingfolder="${workingfolder%/}"
else
	workingfolder="."
fi

if [[ "$argp" = true ]] ; then
	# find semi-repeat-free seeds
	$gcsa2locate --approximate --split-output-matches-graphaligner --overwrite \
		$ignorecharsarg \
		--threads $threads \
		--approximate-edge-match-longest $edgelongestcount \
		$graph \
		$index \
		<(awk 'NR % 4 == 1 || NR % 4 == 2' $reads | sed 's/^@/>/g' | cut -d' ' -f1) \
		"$workingfolder/$(basename $reads)_srf_seeds.gaf"

	# GraphAligner extend
	$graphaligner $extendoptions \
		-t $threads \
		-g $graph \
		-f $reads \
		--realign "$workingfolder/$(basename $reads)_srf_seeds.gaf" \
		-a $alignmentsout
else
	# pipeline of above commands
	$gcsa2locate --approximate --split-output-matches-graphaligner --overwrite \
		$ignorecharsarg \
		--threads $threads \
		--approximate-edge-match-longest $edgelongestcount \
		$graph \
		$index \
		<(awk 'NR % 4 == 1 || NR % 4 == 2' $reads | sed 's/^@/>/g' | cut -d' ' -f1) \
		/dev/stdout | \
	$graphaligner $extendoptions \
		-t $threads \
		-g $graph \
		-f $reads \
		--realign /dev/stdin \
		-a $alignmentsout
fi
